services:
  postgres:
    image: postgres:${DOCKER_POSTGRES_VERSION:-latest}
    container_name: ${DOCKER_POSTGRES_CONTAINER_NAME:-postgres_dev}
    restart: "on-failure:1"
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-U",
          "${POSTGRES_USER:-user}",
          "-d",
          "${POSTGRES_DATABASE:-dev}",
        ]
      interval: 10s
      timeout: 10s
      retries: 3
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE:-dev}
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-user}
